### ISSUE TITLE
Setuptools Pinning Causes Pip Issues

### ISSUE THREAD

**Issue by cernec1999** [apimatic/core-lib-python#49]
**Describe the bug**
Does `setuptools` need to be pinned to `66.0.0`? Your code package (which is used by `squareup`) is causing some issues upon install due to this dependency being pinned. Ideally, pinning should be removed or set to a minimum version.

**To Reproduce**
Simply install a package that has `setuptools` pinned to a later version, such as `maxminddb==2.5.1`, which has the requirement `setuptools>=68.2.2`.

**Expected behavior**
Pinning `setuptools` like this causes the whole python environment to require this version. Simply remove the pinning, if possible.

**Environment**
macOS

**Library version**
0.2.6

**Additional context**
I am using the latest `squareup` package, which has this as a dependency.

**Comment by dirjud** [comment]
I am experiencing the same problem
