### ISSUE TITLE
Dependency on enum34

### ISSUE THREAD

**Issue by lsnliu** [apimatic/core-lib-python#59]
**Describe the bug**
The package has a dependency on enum34 which is no longer required after python 3.6 based on my google research.  Could be wrong entirely.

![image](https://github.com/apimatic/core-lib-python/assets/2326746/c89fbec0-e51e-4ca9-a8b0-f92499bbd301)

This causes the standard class attribute error `AttributeError: module 'enum' has no attribute 'IntFlag'`  in certain environments.  In my specific scenario, it's azure app service. 

**To Reproduce**
1. Reproduction of this bug would require you to have an azure web app for python.
2. deploy any code with your package in the requirements.txt and the server will fail to start and show that error

**Expected behavior**
enum import error should not occur

**Screenshots**

**Environment**
Linux python 3.10.11

**Library version**
0.2.9

**Additional context**
I believe that it doesn't matter if it causes errors in only specific scenarios.  Given this is no longer required post python3.6, it should not be utilized.
thanks

**Comment by sufyankhanrao** [comment]
Hey @lsnliu,
Thank you for reporting this and we are investigating this on our side.

**Comment by lsnliu** [comment]
Thanks for this.

I just tried pip uninstall and pip install again and your package's dependency still includes enum34.  When will that be updated?

![image](https://github.com/apimatic/core-lib-python/assets/2326746/8777ff6b-152b-4ee2-8046-32d1bce7f532)

**Comment by sufyankhanrao** [comment]
> Thanks for this.
> 
> I just tried pip uninstall and pip install again and your package's dependency still includes enum34. When will that be updated?
> 
> ![image](https://private-user-images.githubusercontent.com/2326746/332307983-8777ff6b-152b-4ee2-8046-32d1bce7f532.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNzY3ODMsIm5iZiI6MTcxNjI3NjQ4MywicGF0aCI6Ii8yMzI2NzQ2LzMzMjMwNzk4My04Nzc3ZmY2Yi0xNTJiLTRlZTItODA0Ni0zMmQxYmNlN2Y1MzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjFUMDcyODAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjlkNTFiNmU2YzNkYTg4YWJlNWRmZTkwOGI4Y2ZjOWMyOTc0YzE2YTA5ODIwNjk3ZThlYWMyZmRmYjQ3Y2Y2ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.oJYwEKyFJO0yfz8XI0jrZwJEhWaetjn_0-oyx2C4XaM)

Hey @lsnliu,
This has been addressed in the latest version i.e. `0.2.12`. Can you please retry now?

**Comment by lsnliu** [comment]
Works, thanks!
