### ISSUE TITLE
Update python-dateutil version (5 year old build)

### ISSUE THREAD

**Issue by ZoranPavlovic** [apimatic/core-lib-python#70]
Hello,

Please can we update the lib to use the latest, or at least newer, version of [python-dateutil](https://github.com/dateutil/dateutil)? The one currently referenced is almost 5 years old now and is causing conflicts for any project that wants to use the newer version alongside packages such as [paypal-server-sdk](https://github.com/paypal/PayPal-Python-Server-SDK) which depends on apimatic-python?

Is there any reason we can't move to using python-dateutil 2.9.x in apimatic-core-lib-python?

**Comment by sohaibtariq** [comment]
Hi @ZoranPavlovic, we're adding this to our next release

**Comment by mrafnadeem-apimatic** [comment]
@ZoranPavlovic Thank you for reporting this issue. We have updated this dependency to allow for versions compatible with 2.8 and above. This has now been [released](https://pypi.org/project/apimatic-core/).

**Comment by ZoranPavlovic** [comment]
@sohaibtariq and @mrafnadeem-apimatic  - Thank you very much. Much appreciated!
